
using luau_ffi_protected_pushcclosurek_function_delegate = Luau.Native.lua_CFunction;
using luau_ffi_protected_pushcclosurek_continuation_delegate = Luau.Native.lua_Continuation;
using luau_ffi_protected_newuserdatadtor_destructor_delegate = Luau.Native.lua_UserdataDestructor;

// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Luau.Native
{
    public static unsafe partial class NativeMethods
    {


        public const uint LUAU_PROTECTED_COMPILE_OK = 0;
        public const uint LUAU_PROTECTED_COMPILE_OUT_OF_MEMORY = 1;
        public const uint LUAU_PROTECTED_COMPILE_ERROR = 2;
        public const uint LUAU_ABI_INFO_OK = 0;
        public const uint LUAU_ABI_INFO_BUFFER_TOO_SMALL = 1;
        public const uint LUAU_ABI_INFO_INVALID_ARGUMENT = 2;


        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_abi_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_abi_version();

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_abi_info_v2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_abi_info_v2(luau_ffi_abi_info_v2* info, uint infoSize);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_compile", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_compile(byte* source, nuint size, lua_CompileOptions* options, byte** output, nuint* outputSize);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_checkstack", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_checkstack(lua_State* L, int size, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_newthread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_newthread(lua_State* L, lua_State** result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_resetthread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_resetthread(lua_State* L);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_install_interrupt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_install_interrupt(lua_State* L, void* poll);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_uninstall_interrupt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luau_ffi_protected_uninstall_interrupt(lua_State* L);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_pushvalue", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_pushvalue(lua_State* L, int index);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_pushnil", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_pushnil(lua_State* L);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_pushboolean", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_pushboolean(lua_State* L, int value);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_pushinteger", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_pushinteger(lua_State* L, int value);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_pushinteger64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_pushinteger64(lua_State* L, long value);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_pushunsigned", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_pushunsigned(lua_State* L, uint value);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_pushnumber", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_pushnumber(lua_State* L, double value);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_pushvector", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_pushvector(lua_State* L, float x, float y, float z);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_pushlstring", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_pushlstring(lua_State* L, byte* value, nuint length);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_pushcclosurek", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_pushcclosurek(lua_State* L, lua_CFunction function, byte* debugName, int upvalues, lua_Continuation continuation);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_pushlightuserdatatagged", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_pushlightuserdatatagged(lua_State* L, void* pointer, int tag);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_pushthread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_pushthread(lua_State* L, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_newuserdatatagged", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_newuserdatatagged(lua_State* L, nuint size, int tag, void** result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_newuserdatadtor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_newuserdatadtor(lua_State* L, nuint size, luau_ffi_protected_newuserdatadtor_destructor_delegate destructor, void** result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_newbuffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_newbuffer(lua_State* L, nuint size, void** result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_gettable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_gettable(lua_State* L, int index, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_getfield", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_getfield(lua_State* L, int index, byte* key, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_rawgetfield", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_rawgetfield(lua_State* L, int index, byte* key, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_rawget", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_rawget(lua_State* L, int index, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_rawgeti", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_rawgeti(lua_State* L, int index, int item, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_next", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_next(lua_State* L, int index, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_createtable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_createtable(lua_State* L, int arraySize, int recordSize);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_getmetatable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_getmetatable(lua_State* L, int index, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_getfenv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_getfenv(lua_State* L, int index);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_settable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_settable(lua_State* L, int index);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_setfield", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_setfield(lua_State* L, int index, byte* key);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_rawsetfield", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_rawsetfield(lua_State* L, int index, byte* key);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_rawset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_rawset(lua_State* L, int index);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_rawseti", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_rawseti(lua_State* L, int index, int item);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_setmetatable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_setmetatable(lua_State* L, int index, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_setfenv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_setfenv(lua_State* L, int index, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_load(lua_State* L, byte* chunkName, byte* bytecode, nuint size, int environment, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_gc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_gc(lua_State* L, int operation, int data, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_concat", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_concat(lua_State* L, int count);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_clonefunction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_clonefunction(lua_State* L, int index);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_cleartable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_cleartable(lua_State* L, int index);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_clonetable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_clonetable(lua_State* L, int index);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_ref", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_ref(lua_State* L, int index, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_tolstring", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_tolstring(lua_State* L, int index, byte** result, nuint* length);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_luaL_tolstring", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_luaL_tolstring(lua_State* L, int index, byte** result, nuint* length);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_openlibrary", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_openlibrary(lua_State* L, int library, int* result);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_openlibs", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_openlibs(lua_State* L);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_sandbox", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_sandbox(lua_State* L);

        [DllImport(__DllName, EntryPoint = "ffi_luau_ffi_protected_sandboxthread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luau_ffi_protected_sandboxthread(lua_State* L);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct luau_ffi_abi_info_v2
    {
        public uint struct_size;
        public uint protected_abi_version;
        public byte pointer_size;
        public byte size_t_size;
        public byte little_endian;
        public byte reserved0;
        public uint compile_options_size;
        public uint callbacks_size;
        public int type_nil;
        public int type_boolean;
        public int type_lightuserdata;
        public int type_number;
        public int type_vector;
        public int type_string;
        public int type_table;
        public int type_function;
        public int type_userdata;
        public int type_thread;
        public int type_buffer;
        public int type_integer;
        public int type_class;
        public int type_object;
    }



}
