/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;


use super::luau::*;
use super::luau_require::*;



#[no_mangle]
pub unsafe extern "C" fn ffi_luarequire_pushrequire(
    L: *mut lua_State,
    config_init: luarequire_Configuration_init,
    ctx: *mut c_void
) -> c_int
{
    luarequire_pushrequire(
        L,
        config_init,
        ctx
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luaopen_require(
    L: *mut lua_State,
    config_init: luarequire_Configuration_init,
    ctx: *mut c_void
)
{
    luaopen_require(
        L,
        config_init,
        ctx
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luarequire_pushproxyrequire(
    L: *mut lua_State,
    config_init: luarequire_Configuration_init,
    ctx: *mut c_void
) -> c_int
{
    luarequire_pushproxyrequire(
        L,
        config_init,
        ctx
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luarequire_registermodule(
    L: *mut lua_State
) -> c_int
{
    luarequire_registermodule(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luarequire_clearcacheentry(
    L: *mut lua_State
) -> c_int
{
    luarequire_clearcacheentry(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luarequire_clearcache(
    L: *mut lua_State
) -> c_int
{
    luarequire_clearcache(
        L
    )
}

    