/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;


use super::luau::*;
use super::protected::*;



#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_abi_version(

) -> c_int
{
    luau_ffi_protected_abi_version(

    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_abi_info_v2(
    info: *mut luau_ffi_abi_info_v2,
    infoSize: u32
) -> c_int
{
    luau_ffi_protected_abi_info_v2(
        info,
        infoSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_compile(
    source: *const c_char,
    size: usize,
    options: *mut lua_CompileOptions,
    output: *mut *mut c_char,
    outputSize: *mut usize
) -> c_int
{
    luau_ffi_protected_compile(
        source,
        size,
        options,
        output,
        outputSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_checkstack(
    L: *mut lua_State,
    size: c_int,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_checkstack(
        L,
        size,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_newthread(
    L: *mut lua_State,
    result: *mut *mut lua_State
) -> c_int
{
    luau_ffi_protected_newthread(
        L,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_resetthread(
    L: *mut lua_State
) -> c_int
{
    luau_ffi_protected_resetthread(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_install_interrupt(
    L: *mut lua_State,
    poll: *mut c_void
) -> c_int
{
    luau_ffi_protected_install_interrupt(
        L,
        poll
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_uninstall_interrupt(
    L: *mut lua_State
)
{
    luau_ffi_protected_uninstall_interrupt(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_pushvalue(
    L: *mut lua_State,
    index: c_int
) -> c_int
{
    luau_ffi_protected_pushvalue(
        L,
        index
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_pushnil(
    L: *mut lua_State
) -> c_int
{
    luau_ffi_protected_pushnil(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_pushboolean(
    L: *mut lua_State,
    value: c_int
) -> c_int
{
    luau_ffi_protected_pushboolean(
        L,
        value
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_pushinteger(
    L: *mut lua_State,
    value: c_int
) -> c_int
{
    luau_ffi_protected_pushinteger(
        L,
        value
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_pushinteger64(
    L: *mut lua_State,
    value: i64
) -> c_int
{
    luau_ffi_protected_pushinteger64(
        L,
        value
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_pushunsigned(
    L: *mut lua_State,
    value: c_uint
) -> c_int
{
    luau_ffi_protected_pushunsigned(
        L,
        value
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_pushnumber(
    L: *mut lua_State,
    value: c_double
) -> c_int
{
    luau_ffi_protected_pushnumber(
        L,
        value
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_pushvector(
    L: *mut lua_State,
    x: c_float,
    y: c_float,
    z: c_float
) -> c_int
{
    luau_ffi_protected_pushvector(
        L,
        x,
        y,
        z
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_pushlstring(
    L: *mut lua_State,
    value: *const c_char,
    length: usize
) -> c_int
{
    luau_ffi_protected_pushlstring(
        L,
        value,
        length
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_pushcclosurek(
    L: *mut lua_State,
    function: lua_CFunction,
    debugName: *const c_char,
    upvalues: c_int,
    continuation: lua_Continuation
) -> c_int
{
    luau_ffi_protected_pushcclosurek(
        L,
        function,
        debugName,
        upvalues,
        continuation
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_pushlightuserdatatagged(
    L: *mut lua_State,
    pointer: *mut c_void,
    tag: c_int
) -> c_int
{
    luau_ffi_protected_pushlightuserdatatagged(
        L,
        pointer,
        tag
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_pushthread(
    L: *mut lua_State,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_pushthread(
        L,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_newuserdatatagged(
    L: *mut lua_State,
    size: usize,
    tag: c_int,
    result: *mut *mut c_void
) -> c_int
{
    luau_ffi_protected_newuserdatatagged(
        L,
        size,
        tag,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_newuserdatadtor(
    L: *mut lua_State,
    size: usize,
    destructor: luau_ffi_protected_destructor,
    result: *mut *mut c_void
) -> c_int
{
    luau_ffi_protected_newuserdatadtor(
        L,
        size,
        destructor,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_newbuffer(
    L: *mut lua_State,
    size: usize,
    result: *mut *mut c_void
) -> c_int
{
    luau_ffi_protected_newbuffer(
        L,
        size,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_gettable(
    L: *mut lua_State,
    index: c_int,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_gettable(
        L,
        index,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_getfield(
    L: *mut lua_State,
    index: c_int,
    key: *const c_char,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_getfield(
        L,
        index,
        key,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_rawgetfield(
    L: *mut lua_State,
    index: c_int,
    key: *const c_char,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_rawgetfield(
        L,
        index,
        key,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_rawget(
    L: *mut lua_State,
    index: c_int,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_rawget(
        L,
        index,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_rawgeti(
    L: *mut lua_State,
    index: c_int,
    item: c_int,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_rawgeti(
        L,
        index,
        item,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_next(
    L: *mut lua_State,
    index: c_int,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_next(
        L,
        index,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_createtable(
    L: *mut lua_State,
    arraySize: c_int,
    recordSize: c_int
) -> c_int
{
    luau_ffi_protected_createtable(
        L,
        arraySize,
        recordSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_getmetatable(
    L: *mut lua_State,
    index: c_int,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_getmetatable(
        L,
        index,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_getfenv(
    L: *mut lua_State,
    index: c_int
) -> c_int
{
    luau_ffi_protected_getfenv(
        L,
        index
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_settable(
    L: *mut lua_State,
    index: c_int
) -> c_int
{
    luau_ffi_protected_settable(
        L,
        index
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_setfield(
    L: *mut lua_State,
    index: c_int,
    key: *const c_char
) -> c_int
{
    luau_ffi_protected_setfield(
        L,
        index,
        key
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_rawsetfield(
    L: *mut lua_State,
    index: c_int,
    key: *const c_char
) -> c_int
{
    luau_ffi_protected_rawsetfield(
        L,
        index,
        key
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_rawset(
    L: *mut lua_State,
    index: c_int
) -> c_int
{
    luau_ffi_protected_rawset(
        L,
        index
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_rawseti(
    L: *mut lua_State,
    index: c_int,
    item: c_int
) -> c_int
{
    luau_ffi_protected_rawseti(
        L,
        index,
        item
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_setmetatable(
    L: *mut lua_State,
    index: c_int,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_setmetatable(
        L,
        index,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_setfenv(
    L: *mut lua_State,
    index: c_int,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_setfenv(
        L,
        index,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_load(
    L: *mut lua_State,
    chunkName: *const c_char,
    bytecode: *const c_char,
    size: usize,
    environment: c_int,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_load(
        L,
        chunkName,
        bytecode,
        size,
        environment,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_gc(
    L: *mut lua_State,
    operation: c_int,
    data: c_int,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_gc(
        L,
        operation,
        data,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_concat(
    L: *mut lua_State,
    count: c_int
) -> c_int
{
    luau_ffi_protected_concat(
        L,
        count
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_clonefunction(
    L: *mut lua_State,
    index: c_int
) -> c_int
{
    luau_ffi_protected_clonefunction(
        L,
        index
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_cleartable(
    L: *mut lua_State,
    index: c_int
) -> c_int
{
    luau_ffi_protected_cleartable(
        L,
        index
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_clonetable(
    L: *mut lua_State,
    index: c_int
) -> c_int
{
    luau_ffi_protected_clonetable(
        L,
        index
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_ref(
    L: *mut lua_State,
    index: c_int,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_ref(
        L,
        index,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_tolstring(
    L: *mut lua_State,
    index: c_int,
    result: *mut *const c_char,
    length: *mut usize
) -> c_int
{
    luau_ffi_protected_tolstring(
        L,
        index,
        result,
        length
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_luaL_tolstring(
    L: *mut lua_State,
    index: c_int,
    result: *mut *const c_char,
    length: *mut usize
) -> c_int
{
    luau_ffi_protected_luaL_tolstring(
        L,
        index,
        result,
        length
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_openlibrary(
    L: *mut lua_State,
    library: c_int,
    result: *mut c_int
) -> c_int
{
    luau_ffi_protected_openlibrary(
        L,
        library,
        result
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_openlibs(
    L: *mut lua_State
) -> c_int
{
    luau_ffi_protected_openlibs(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_sandbox(
    L: *mut lua_State
) -> c_int
{
    luau_ffi_protected_sandbox(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn ffi_luau_ffi_protected_sandboxthread(
    L: *mut lua_State
) -> c_int
{
    luau_ffi_protected_sandboxthread(
        L
    )
}
