using System.Reflection.PortableExecutable;
using Luau.SourceGenerator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Luau.SourceGenerator.Tests;

public sealed class LuauLibraryGeneratorTests
{
    const string ConsumerPath = @"C:\probe\Consumer.cs";

    const string ApiSource = """
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Luau
{
    [AttributeUsage(AttributeTargets.Class)]
    public sealed class LuauLibraryAttribute : Attribute
    {
        public LuauLibraryAttribute(string name) { }
    }

    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property | AttributeTargets.Method)]
    public sealed class LuauMemberAttribute : Attribute
    {
        public LuauMemberAttribute(string? name = null) { }
    }

    [AttributeUsage(AttributeTargets.Parameter)]
    public sealed class FromLuauStateAttribute : Attribute { }

    public interface ILuauLibrary
    {
        void RegisterTo(LuauState state);
    }

    public sealed class LuauException : Exception
    {
        public LuauException(string message) : base(message) { }
    }

    public sealed class LuauFunction { }
    public sealed class LuauBuffer { }
    public sealed class LuauUserData { }
    public readonly struct LuauValue { }

    public sealed class LuauTable : IDisposable
    {
        public object? this[string key] { set { } }
        public void RawSet(string key, LuauValue value) { }
        public void Dispose() { }
    }

    public sealed class LuauState
    {
        public object? this[string key] { set { } }
        public LuauTable CreateTable() => new();
        public LuauFunction CreateFunction(string? name, Action<LuauCallContext> callback) => new();
        public LuauFunction CreateAsyncFunction(string? name, Func<LuauCallContext, ValueTask> callback) => new();
        public void SetMetatable(LuauTable table, LuauTable metatable) { }
    }

    public sealed class LuauCallContext
    {
        public int ArgumentCount => 0;
        public LuauState State => new();
        public CancellationToken CancellationToken => default;
        public T Read<T>(int zeroBasedIndex) => default!;
        public void Return<T>(T value) { }
    }
}
""";

    const string RepresentativeSource = """
using System.Threading;
using Luau;

namespace Demo;

[LuauLibrary("ship\"yard")]
public partial class ShipApi
{
    [LuauMember("fuel-level")]
    public int Fuel { get; set; }

    [LuauMember("serial\\code")]
    public readonly string Serial = "S-1";

    [LuauMember("mix-it")]
    public int Mix(
        int first,
        LuauCallContext callContext,
        [FromLuauState] LuauState state,
        CancellationToken cancellationToken,
        string second) => first + second.Length;
}
""";

    const string RepresentativeSnapshot = """
// <auto-generated/>

namespace Demo
{
    partial class ShipApi : global::Luau.ILuauLibrary
    {
        void global::Luau.ILuauLibrary.RegisterTo(global::Luau.LuauState state)
        {
            using var table = state.CreateTable();
            using var metatable = state.CreateTable();

            var function0 = state.CreateFunction("ship\"yard.mix-it", context =>
            {
                if (context.ArgumentCount < 2)
                {
                    throw new global::Luau.LuauException("Host function 'ship\"yard.mix-it' expects at least 2 argument(s).");
                }
                var arg0 = context.Read<global::System.Int32>(0);
                var arg1 = context;
                var arg2 = context.State;
                var arg3 = context.CancellationToken;
                var arg4 = context.Read<global::System.String>(1);
                var result = this.Mix(arg0, arg1, arg2, arg3, arg4);
                context.Return(result);
            });

            metatable["__index"] = state.CreateFunction("ship\"yard.__index", context =>
            {
                var key = context.Read<global::System.String>(1);
                switch (key)
                {
                    case "fuel-level":
                        context.Return(this.Fuel);
                        break;
                    case "serial\\code":
                        context.Return(this.Serial);
                        break;
                    case "mix-it":
                        context.Return(function0);
                        break;
                }
            });

            metatable["__newindex"] = state.CreateFunction("ship\"yard.__newindex", context =>
            {
                var key = context.Read<global::System.String>(1);
                switch (key)
                {
                    case "fuel-level":
                        this.Fuel = context.Read<global::System.Int32>(2);
                        break;
                    case "serial\\code":
                        throw new global::Luau.LuauException($"cannot set readonly member '{key}'");
                    case "mix-it":
                        throw new global::Luau.LuauException($"cannot set readonly member '{key}'");
                    default:
                        throw new global::Luau.LuauException($"cannot set unknown member '{key}'");
                }
            });

            metatable["__metatable"] = "protected Luau host library";
            state.SetMetatable(table, metatable);
            state["ship\"yard"] = table;
        }
    }
}
""";

    static readonly CSharpParseOptions ParseOptions = new(LanguageVersion.Preview);

    static readonly MetadataReference[] PlatformReferences =
        Directory.EnumerateFiles(
                System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory(),
                "*.dll")
            .Where(IsManagedAssembly)
            .Select(path => MetadataReference.CreateFromFile(path))
            .ToArray();

    [Fact]
    public void RepresentativeLibraryGeneratesStableSafeSourceAndCompiles()
    {
        var result = RunGenerator(
            CreateCompilation(RepresentativeSource),
            out var outputCompilation);

        Assert.Empty(result.Diagnostics);
        AssertNoErrors(outputCompilation);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        Assert.Equal(Normalize(RepresentativeSnapshot), Normalize(generated));
        Assert.DoesNotContain("ToValue", generated, StringComparison.Ordinal);
        Assert.DoesNotContain("Push", generated, StringComparison.Ordinal);
        Assert.DoesNotContain("Native", generated, StringComparison.Ordinal);
        Assert.DoesNotContain("CallerFilePath", generated, StringComparison.Ordinal);
        Assert.DoesNotContain("PushTable", generated, StringComparison.Ordinal);
    }

    [Fact]
    public void PropertyAccessRequiresPublicAccessors()
    {
        const string source = """
using Luau;

[LuauLibrary("properties")]
public partial class PropertyApi
{
    [LuauMember("read-only")] public int ReadOnly { get; private set; }
    [LuauMember("write-only")] public int WriteOnly { private get; set; }
    [LuauMember("read-write")] public int ReadWrite { get; set; }
    [LuauMember("init-only")] public int InitOnly { get; init; }
}
""";

        var result = RunGenerator(CreateCompilation(source), out var outputCompilation);

        Assert.Empty(result.Diagnostics);
        AssertNoErrors(outputCompilation);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        Assert.Contains("context.Return(this.ReadOnly);", generated, StringComparison.Ordinal);
        Assert.DoesNotContain("this.ReadOnly =", generated, StringComparison.Ordinal);
        Assert.DoesNotContain("context.Return(this.WriteOnly);", generated, StringComparison.Ordinal);
        Assert.Contains(
            "this.WriteOnly = context.Read<global::System.Int32>(2);",
            generated,
            StringComparison.Ordinal);
        Assert.Contains("context.Return(this.ReadWrite);", generated, StringComparison.Ordinal);
        Assert.Contains(
            "this.ReadWrite = context.Read<global::System.Int32>(2);",
            generated,
            StringComparison.Ordinal);
        Assert.Contains("context.Return(this.InitOnly);", generated, StringComparison.Ordinal);
        Assert.DoesNotContain("this.InitOnly =", generated, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("bool")]
    [InlineData("byte")]
    [InlineData("sbyte")]
    [InlineData("short")]
    [InlineData("ushort")]
    [InlineData("int")]
    [InlineData("uint")]
    [InlineData("long")]
    [InlineData("ulong")]
    [InlineData("float")]
    [InlineData("double")]
    [InlineData("string")]
    [InlineData("System.Numerics.Vector3")]
    [InlineData("LuauValue")]
    [InlineData("LuauFunction")]
    [InlineData("LuauTable")]
    [InlineData("LuauBuffer")]
    [InlineData("LuauState")]
    [InlineData("LuauUserData")]
    public void ExplicitLuauValueConversionTypesAreSupported(string typeName)
    {
        var source = $$"""
using Luau;

[LuauLibrary("supported")]
public partial class SupportedApi
{
    [LuauMember] public {{typeName}} Echo({{typeName}} value) => value;
}
""";

        var result = RunGenerator(CreateCompilation(source), out var outputCompilation);

        Assert.Empty(result.Diagnostics);
        AssertNoErrors(outputCompilation);
        Assert.Single(result.GeneratedSources);
    }

    [Theory]
    [InlineData("char")]
    [InlineData("decimal")]
    [InlineData("object")]
    [InlineData("System.DateTime")]
    [InlineData("System.Guid")]
    [InlineData("CapabilityToken")]
    public void OtherManagedValueTypesAreRejectedAtGenerationTime(string typeName)
    {
        var source = $$"""
using Luau;

public readonly struct CapabilityToken { }

[LuauLibrary("unsupported-value")]
public partial class UnsupportedValueApi
{
    [LuauMember] public {{typeName}} Echo({{typeName}} value) => value;
}
""";

        var result = RunGenerator(CreateCompilation(source), out _);

        var diagnostic = Assert.Single(result.Diagnostics, diagnostic => diagnostic.Id == "LUAU005");
        Assert.Contains("Luau value conversion", diagnostic.GetMessage(), StringComparison.Ordinal);
        Assert.Empty(result.GeneratedSources);
    }

    [Theory]
    [InlineData("[LuauMember] public CapabilityToken Value;", "field type")]
    [InlineData("[LuauMember] public CapabilityToken Value { get; set; }", "property type")]
    [InlineData(
        "[LuauMember] public int Consume(CapabilityToken value) => 1;",
        "script argument type")]
    public void UnsupportedValueTypesAreRejectedAcrossMemberShapes(
        string member,
        string expectedMessage)
    {
        var source = $$"""
using Luau;

public readonly struct CapabilityToken { }

[LuauLibrary("unsupported-shape")]
public partial class UnsupportedShapeApi
{
    {{member}}
}
""";

        var result = RunGenerator(CreateCompilation(source), out _);

        var diagnostic = Assert.Single(result.Diagnostics, diagnostic => diagnostic.Id == "LUAU005");
        Assert.Contains(
            expectedMessage,
            diagnostic.GetMessage(),
            StringComparison.OrdinalIgnoreCase);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void AsyncReturnShapesUseOneValueTaskCallbackPathAndCompile()
    {
        const string source = """
using System.Threading.Tasks;
using Luau;

[LuauLibrary("async")]
public partial class AsyncApi
{
    [LuauMember] public Task TaskOnly() => Task.CompletedTask;
    [LuauMember] public Task<int> TaskValue() => Task.FromResult(1);
    [LuauMember] public ValueTask ValueTaskOnly() => ValueTask.CompletedTask;
    [LuauMember] public static ValueTask<string> ValueTaskValue() => ValueTask.FromResult("ok");
}
""";

        var result = RunGenerator(CreateCompilation(source), out var outputCompilation);

        Assert.Empty(result.Diagnostics);
        AssertNoErrors(outputCompilation);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();
        Assert.Equal(4, Count(generated, "CreateAsyncFunction("));
        Assert.Contains("await this.TaskOnly();", generated, StringComparison.Ordinal);
        Assert.Contains("var result = await this.TaskValue();", generated, StringComparison.Ordinal);
        Assert.Contains("await this.ValueTaskOnly();", generated, StringComparison.Ordinal);
        Assert.Contains(
            "var result = await global::AsyncApi.ValueTaskValue();",
            generated,
            StringComparison.Ordinal);
        Assert.Equal(2, Count(generated, "context.Return(result);"));
    }

    [Theory]
    [InlineData("[LuauLibrary(\"bad\")] public class Api { }", "LUAU001")]
    [InlineData("public class Outer { [LuauLibrary(\"bad\")] public partial class Api { } }", "LUAU002")]
    [InlineData("[LuauLibrary(\"bad\")] public abstract partial class Api { }", "LUAU003")]
    public void InvalidLibraryDeclarationsReportActionableDiagnostics(string declaration, string diagnosticId)
    {
        var result = RunGenerator(
            CreateCompilation("using Luau;\n" + declaration),
            out _);

        Assert.Contains(result.Diagnostics, diagnostic => diagnostic.Id == diagnosticId);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void DuplicateLuauNamesAcrossMemberKindsAreRejected()
    {
        const string source = """
using Luau;

[LuauLibrary("duplicate")]
public partial class Api
{
    [LuauMember("same")] public int Value;
    [LuauMember("same")] public int GetValue() => Value;
}
""";

        var result = RunGenerator(CreateCompilation(source), out _);

        var diagnostic = Assert.Single(result.Diagnostics, diagnostic => diagnostic.Id == "LUAU004");
        Assert.Contains("same", diagnostic.GetMessage(), StringComparison.Ordinal);
        Assert.Empty(result.GeneratedSources);
    }

    public static TheoryData<string, string> UnsupportedSignatures => new()
    {
        {
            "[LuauMember] public T Generic<T>(T value) => value;",
            "generic"
        },
        {
            "[LuauMember] public void ByRef(ref int value) { }",
            "ref"
        },
        {
            "[LuauMember] public int this[int index] => index;",
            "indexers"
        },
        {
            "[LuauMember] public async void FireAndForget() { await System.Threading.Tasks.Task.Yield(); }",
            "async void"
        },
        {
            "[LuauMember] public void WrongInjection([FromLuauState] int value) { }",
            "FromLuauState"
        },
    };

    [Theory]
    [MemberData(nameof(UnsupportedSignatures))]
    public void UnsupportedMemberSignaturesReportDiagnostics(string member, string expectedMessage)
    {
        var source = $$"""
using Luau;

[LuauLibrary("unsupported")]
public partial class Api
{
    {{member}}
}
""";

        var result = RunGenerator(CreateCompilation(source), out _);

        var diagnostic = Assert.Single(result.Diagnostics, diagnostic => diagnostic.Id == "LUAU005");
        Assert.Contains(expectedMessage, diagnostic.GetMessage(), StringComparison.OrdinalIgnoreCase);
        Assert.Empty(result.GeneratedSources);
    }

    static CSharpCompilation CreateCompilation(string source)
    {
        var apiTree = CSharpSyntaxTree.ParseText(ApiSource, ParseOptions, @"C:\probe\LuauApi.cs");
        var consumerTree = CSharpSyntaxTree.ParseText(source, ParseOptions, ConsumerPath);
        return CSharpCompilation.Create(
            "LuauConsumer",
            [apiTree, consumerTree],
            PlatformReferences,
            new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                allowUnsafe: true,
                nullableContextOptions: NullableContextOptions.Enable));
    }

    static GeneratorRunResult RunGenerator(
        CSharpCompilation compilation,
        out Compilation outputCompilation)
    {
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            [new LuauLibraryGenerator().AsSourceGenerator()],
            parseOptions: ParseOptions);

        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out outputCompilation,
            out var generatorDiagnostics);

        Assert.Empty(generatorDiagnostics.Where(
            diagnostic => diagnostic.Severity == DiagnosticSeverity.Error &&
                          diagnostic.Id == "CS8785"));
        return driver.GetRunResult().Results.Single();
    }

    static void AssertNoErrors(Compilation compilation)
    {
        var errors = compilation.GetDiagnostics()
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .Select(diagnostic => diagnostic.ToString())
            .ToArray();

        Assert.True(errors.Length == 0, string.Join(Environment.NewLine, errors));
    }

    static string Normalize(string source) =>
        source.Replace("\r\n", "\n", StringComparison.Ordinal).Trim();

    static int Count(string source, string value)
    {
        var count = 0;
        var index = 0;
        while ((index = source.IndexOf(value, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += value.Length;
        }

        return count;
    }

    static bool IsManagedAssembly(string path)
    {
        using var stream = File.OpenRead(path);
        using var reader = new PEReader(stream);
        return reader.HasMetadata;
    }
}
