<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net8.0;netstandard2.1</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Luau.Native\Luau.Native.csproj" />
    <ProjectReference Include="..\Luau.SourceGenerator\Luau.SourceGenerator.csproj" ReferenceOutputAssembly="false" />

  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework) == 'netstandard2.1'">
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <Compile Remove="FileSystemLuauRequirer.cs" />
    <Compile Remove="Internal\DictionaryJsonSerializeContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PolySharp" Version="1.15.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
